addressfield.subdivision.*:
  type: config_entity
  label: 'Subdivision'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: label
      label: 'Name'
      translatable: true
    code:
      type: string
      label: 'Code'
    parent_id:
      type: string
      label: 'Parent ID'
    country_code:
      type: string
      label: 'Country code'
    status:
      label: Status
      type: boolean

addressfield.address_format.*:
  type: config_entity
  label: 'Address format'
  mapping:
    countryCode:
      type: string
      label: 'Country code'
    format:
      type: string
      label: 'Format'
    requiredFields:
      type: array
      label: 'Required fields'
    uppercaseFields:
      type: array
      label: 'Uppercase Fields'
    administrativeAreaType:
      type: string
      label: 'Administrative area type'
    localityType:
      type: string
      label: 'Locality type'
    dependentLocalityType:
      type: string
      label: 'Dependent locality type'
    postalCodeType:
      type: string
      label: 'Postal code type'
    postalCodePattern:
      type: string
      label: 'Postal code pattern'
    postalCodePrefix:
      type: string
      label: 'Postal code prefix'
    status:
      label: Status
      type: boolean
